// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":true,"description":"メニュー画面のレイアウトを変更します。","parameters":{}},
{"name":"MOG_TitlePictureCom","status":true,"description":"(v1.3) Adiciona comandos em imagens no lugar da janela.","parameters":{"Title Sprite":"true","Title Sprite X-Axis":"0","Title Sprite Y-Axis":"0","Cursor Visible":"false","Cursor Wave Animation":"false","Cursor X-Axis":"8","Cursor Y-Axis":"-10","Command Pos 1":"255,432","Command Pos 2":"255,477","Command Pos 3":"255,522","Command Pos 4":"367,466","Command Pos 5":"345,498","Command Pos 6":"345,530","Command Pos 7":"0,192","Command Pos 8":"0,224","Command Pos 9":"0,256","Command Pos 10":"0,288"}},
{"name":"global_k","status":true,"description":"グローバルスクリプト記述プラグイン k","parameters":{}},
{"name":"liply_WinChrome_scroll_patch","status":true,"description":"Windows Chrome scroll patch","parameters":{}},
{"name":"liply_onBitmapLoad_patch","status":true,"description":"","parameters":{}},
{"name":"liply_WaitForImage","status":true,"description":"","parameters":{}},
{"name":"liply_Controller","status":true,"description":"liply_Controller","parameters":{"Show in PC":"off"}},
{"name":"global_object","status":true,"description":"グローバルスクリプト記述プラグイン","parameters":{}},
{"name":"liply_preferAutoDetect","status":true,"description":"","parameters":{}},
{"name":"liply_CallCutIn","status":true,"description":"","parameters":{}}
];
